### ISSUE TITLE
建议在角色页面去掉凯特或是在后面写上(慎用)

### ISSUE THREAD

**Issue by KudouShinnyan** [jie65535/GrasscutterCommandGenerator#1]
如题, 莪的号加了凯特之后被莪玩废了, 一开始是把凯特加入队伍切换不过去, 然后干脆在队伍里只加入凯特一个人, 退出队伍编辑页面之后悲催了, 动弹不得, 也不能进队伍配置的页面了, 退出游戏重进也没好转, 想用同一个账号和uid, 尝试删除账号重建但它没删除数据, 还是一样的状态

**Comment by KudouShinnyan** [comment]
(应该也有其他官服未使用的角色也会造成这样的局面)

**Comment by jie65535** [comment]
合理的建议，我会在页面上增加警告标识，告诉用户可能的后果并请用户在尝试生成官方未使用的角色前再三考虑。
