### ISSUE TITLE
修改完卡池后 抽卡会卡在天空

### ISSUE THREAD

**Issue by neolhfs** [jie65535/GrasscutterCommandGenerator#100]
修改完卡池后 抽卡会卡在天空，必须重启游戏。。。

**Comment by jie65535** [comment]
可是这和我一个生成卡池文件的又有什么关系呢 XD

**Comment by neolhfs** [comment]
就是我用编辑器，把3星和4星的全部取消掉，然后全部都是5星，reload之后抽卡就会卡主 这个是割草机自身的问题吗

**Comment by jie65535** [comment]
不清楚噢，帮不了你太多
