### ISSUE TITLE
功能需求：修改指令格式

### ISSUE THREAD

**Issue by asdls** [jie65535/GrasscutterCommandGenerator#106]
大致如图所示
![测试](https://user-images.githubusercontent.com/82398573/187033697-f77a0ac6-3caf-42bd-83ab-3d7d63f2ace8.jpg)
不会编程，p一下大概
让玩家修改和服务器一样的指令格式，就算后续有变动也不会处于无法正常执行的状态

**Comment by jie65535** [comment]
现在的设计是在首页选择使用的gc版本，以自动切换兼容的指令。_（虽然暂时只有是否>=1.2.2的选项，计划中是一个下拉框）_

你的需求是允许用户自定义指令生成的格式吗？

**Comment by asdls** [comment]
> 现在的设计是在首页选择使用的gc版本，以自动切换兼容的指令。_（虽然暂时只有>=1.2.2的选项，计划中是一个下拉框）_
> 
> 你的需求是允许用户自定义指令生成的格式吗？
是.，你这样一说突然感觉我的功能用不着了...

**Comment by jie65535** [comment]
如果想要生成旧版本的命令，可以取消勾选主页的那个选项，就可以生成以前的命令了。
说起来1.2.3和1.2.2的命令也有一些差异，看来这个下拉框现在就可以实现了。
