### ISSUE TITLE
功能需求：切换主角属性

### ISSUE THREAD

**Issue by sonofrain** [jie65535/GrasscutterCommandGenerator#107]
神像无法互动，也就无法测试草主和雷主，希望添加这个功能。
或者如果已经有的话希望能指导我一下，我确实在程序内翻遍了也没找到orz

**Comment by jie65535** [comment]
有一个插件可以切换主角的属性，可以上频道找找

**Comment by jie65535** [comment]
https://github.com/Penelopeep/SwitchElementTraveller
