### ISSUE TITLE
无法导入GOOD存档

### ISSUE THREAD

**Issue by Sev73n** [jie65535/GrasscutterCommandGenerator#113]
![image](https://user-images.githubusercontent.com/16495885/189254716-c4467ed0-291c-4649-a207-10021ccdb2ec.png)
已经成功连接了本地服务器
成功执行过give命令
当时导入存档的按钮是灰的 已经有了data json文件
![image](https://user-images.githubusercontent.com/16495885/189254772-20306a43-fc7c-4414-b6ff-517e8ed4fb77.png)

**Comment by jie65535** [comment]
需要安装远程执行插件 [OpenCommand](https://github.com/jie65535/gc-opencommand-plugin) ，就是上面那个打叉的连接标签。
