### ISSUE TITLE
[功能请求] 自定义资源版本

### ISSUE THREAD

**Issue by FISHandCHEAP** [jie65535/GrasscutterCommandGenerator#129]
就是在工具主界面，类似于设置GC版本那样，给一个可以设置工具的内置资源的版本的选项

比如说我想用这工具适配3.1的游戏版本，设置之后，在生成、场景等选项卡里面就不会显示高版本的相关内容，以免在使用错误的命令之后导致游戏BUG

**Comment by jie65535** [comment]
错误的命令会有错误提示，资源区分版本没有计划做。
