### ISSUE TITLE
[功能请求] 工具配置文件导出

### ISSUE THREAD

**Issue by FISHandCHEAP** [jie65535/GrasscutterCommandGenerator#130]
建议把工具的配置文件从userdata文件夹移到工具的同级目录下，并且在启动的时候自动读取配置

**Comment by jie65535** [comment]
工具本身就可以识别目录下的配置文件，只需要将[该文件](https://github.com/jie65535/GrasscutterCommandGenerator/blob/main/Source/GrasscutterTools/App.config)命名为`GrasscutterTools.exe.config`放在同级目录，即可识别。

不过用户设置只有在首次加载时识别。

**Comment by FISHandCHEAP** [comment]
那工具怎么生成一份配置文件呢？工具又是读取哪个文件知道自己是不是第一次载入呢

**Comment by jie65535** [comment]
就像我说的，你只需要将那个文件重命名，就是一份可识别的配置文件了。
它会先读取程序目录下的，然后再读取用户目录下的配置。

**Comment by FISHandCHEAP** [comment]
看了一下，确实是行的，虽然可读性不强

说起来，GC 1.4.1更新了，请作者大大适配一下~
