### ISSUE TITLE
[feat.] Command combinations for "Custom" 

### ISSUE THREAD

**Issue by EgorBron** [jie65535/GrasscutterCommandGenerator#131]
Think support for multiple commands per tag in "Custom" tab may be useful.
> *For example: I want to reset constellations of all characters and then kick myself from server (imagine that I do it often). This "script" can help me:*
```shell
/resetconst all
/kick
```
> *It will be cool if it be able to execute by 1 mouse click (oh, that laziness)*

**Comment by jie65535** [comment]
![multiple commands](https://user-images.githubusercontent.com/29452349/197369563-30e7ca77-6d2d-439a-95ed-7f0c1d857d5d.png)

I do this in my other tools, just because I'm too lazy to update this project in a while.

I'll put it on the plan, thanks for the suggestion!

**Comment by jie65535** [comment]
[GrasscutterTools-v1.7.0-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9845700/GrasscutterTools-v1.7.0-debug.exe.zip)
Command combinations are now supported, can you help me test it?

**Comment by EgorBron** [comment]
> [GrasscutterTools-v1.7.0-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9845700/GrasscutterTools-v1.7.0-debug.exe.zip) Command combinations are now supported, can you help me test it?

Sorry, no, because I don't have actual version of Genshin for now (only 2.7 but that always throws 502 error while I trying to connect to Grasscutter)

**Comment by EgorBron** [comment]
@jie65535  I managed to fix the server. And yes, the function works just fine!
