### ISSUE TITLE
[功能请求] GC已发布了1.4.2版本，请求适配

### ISSUE THREAD

**Issue by FISHandCHEAP** [jie65535/GrasscutterCommandGenerator#132]
GC已发布了1.4.2版本，请求适配

**Comment by jie65535** [comment]
目前没发现有什么指令上大的更新，所以工具里只是在添加角色时可以设置技能等级之类的，你可以下载以下文件试用，测试足够后我会发布正式版本。

[GrasscutterTools-v1.7.0-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9871231/GrasscutterTools-v1.7.0-debug.exe.zip)

**Comment by jie65535** [comment]
我刚刚注意到1.4.2可以设置所有角色命座，我看到了你关于所有角色技能的issue，可以加内测群457427536交流新的功能实现。
