### ISSUE TITLE
[功能请求] 支持 AttackModifier 和 AttackInfusedWithItem 插件指令

### ISSUE THREAD

**Issue by kamanya** [jie65535/GrasscutterCommandGenerator#141]
目前有些plugins有支援普攻或E Q spawn怪物 但指令是 /at https://github.com/snoobi-seggs/AttackInfusedWithItem
可否自定议指令好容易使用 AttackInfusedWithItem
即 /at spawnid 距离 高度 数量 扩散 角度
而这位作者还可以为不同人物增加自定义 spawnid 并独立存档设定 https://github.com/NotThorny/AttackModifier
即 /at set n spawnid (为普攻增加spawn) /at set e spawnid  (为E技能增加spawn) /at set q spawnid (为Q技能增加spawn) 
目前都是借由生成介面生成怪物等ID 得到/spawn id x1 lv1 等 可否把 /spawn 改为自订义的 /at  方便使用这两个plusins
自定义指令1 自订义参数1 spawnid 自定义参数2 自定义参数3 自定义参数4 自定义参数5 自定义参数6 自定义参数7 空白就是不使用
谢谢

**Comment by jie65535** [comment]
现已实现，正在内测阶段，你可以加入我们的内测Q群获取测试版本进行体验。或者稍等一段时间将会发布更新。
感谢你的建议

**Comment by kamanya** [comment]
謝謝 但我沒有辦法辦QQ 台灣電話號碼限制
