### ISSUE TITLE
Shop.json在哪啊

### ISSUE THREAD

**Issue by kadlsl** [jie65535/GrasscutterCommandGenerator#142]

**Comment by kadlsl** [comment]
shop.json 找不到

**Comment by jie65535** [comment]
需要在服务端jar所在目录创建一个data文件夹，将Shop.json放在里面即可识别。

在最新测试版本中，可以解析`ShopGoodsExcelConfigData.json`，你可以加入内测群获取测试版本，在不久后将会发布。
