### ISSUE TITLE
卡池编辑器里面预制为妮露加载出错

### ISSUE THREAD

**Issue by 35860368** [jie65535/GrasscutterCommandGenerator#156]
在v1.7.3 版本里面的卡池编辑器里面预制为妮露 这个几个属性
  "prefabPath":"GachaShowPanel_A100",
  "previewPrefabPath":"UI_Tab_GachaShowPanel_A100",
  "titlePath":"UI_GACHA_SHOW_PANEL_A100_TITLE", 
在 游戏版本：3.2.0
 Grasscutter 版本：1.4.3-dev- 里面加载出错

**Comment by jie65535** [comment]
出错的具体错误信息是什么，请附带日志以便于解决

**Comment by 35860368** [comment]
但设置奖池属性
"prefabPath":"GachaShowPanel_A100",
"previewPrefabPath":"UI_Tab_GachaShowPanel_A100",
"titlePath":"UI_GACHA_SHOW_PANEL_A100_TITLE",
为A100的时候，在进入游戏后，切换到祈愿抽卡的界面时，会提示加载错误，当时卡池还是可以抽卡，只是加载不出卡池界面信息，当换成其他除了A100其他的属性时，卡池界面信息显示正常，我的猜想是应该A100匹配不到游戏的卡池界面信息

**Comment by 35860368** [comment]
> 出错的具体错误信息是什么，请附带日志以便于解决

但设置奖池属性
"prefabPath":"GachaShowPanel_A100",
"previewPrefabPath":"UI_Tab_GachaShowPanel_A100",
"titlePath":"UI_GACHA_SHOW_PANEL_A100_TITLE",
为A100的时候，在进入游戏后，切换到祈愿抽卡的界面时，会提示加载错误，当时卡池还是可以抽卡，只是加载不出卡池界面信息，当换成其他除了A100其他的属性时，卡池界面信息显示正常，我的猜想是应该A100匹配不到游戏的卡池界面信息

**Comment by jie65535** [comment]
这可能和资源有关，暂时先禁用A100这个ID
