### ISSUE TITLE
1.7.3打开工具之后界面消失，但工具仍然运行

### ISSUE THREAD

**Issue by RX6800Super** [jie65535/GrasscutterCommandGenerator#161]

**Comment by jie65535** [comment]
目前暂时无法复现，怀疑和设置文件有关，根据其他人的经验，改一下可执行文件名字可以打开。

待解决

**Comment by RX6800Super** [comment]
了解了，解压出来的文件改名之后的确可以使用
不能用解压出来的名字"GrasscutterTools-v1.7.3.exe"
随便改一个名字或者少一个字符好像就可以

**Comment by jie65535** [comment]
已经发现问题根源，是最小化时退出软件，会导致下次启动时重置窗口位置时出错。
在v1.7.6版本中已修复，感谢反馈。

**Comment by RX6800Super** [comment]
作者辛苦了，感谢

**Comment by RX6800Super** [comment]
刚才试了试，找到一种1.7.3最小化退出之后的解决办法：
运行Grasscutter Tools v1.7.3 (此时应该有工具运行但不显示界面)
打开任务管理器，找到运行中的Grasscutter Tools，展开折叠，找到Grasscutter Tools v1.7.3的标签，右键点击，然后点击最大化，再双击界面回到正常大小，此时即可关闭Grasscutter Tools，下次打开就恢复正常了
