### ISSUE TITLE
make searching items menu insensitive to capitalization 

### ISSUE THREAD

**Issue by rsmyst** [jie65535/GrasscutterCommandGenerator#163]
It's annoying to search for something and it won't pup up because you didn't capitalize the word correctly. fix would be appreciated. or maybe a toggle for it. thanks! awesome app.

**Comment by jie65535** [comment]
[GrasscutterTools-v1.7.5-d1.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/10109958/GrasscutterTools-v1.7.5-d1.exe.zip)
