### ISSUE TITLE
Can't close program

### ISSUE THREAD

**Issue by Overwrited** [jie65535/GrasscutterCommandGenerator#164]
I didn't found any "GrassCutter" folder in In AppData/Local (only "io.grasscutter"). And I can't close program due this bug.  Should I create this folder manually? 

![изображение_2022-12-01_134247965](https://user-images.githubusercontent.com/76729429/205032421-0de1fe1c-6fc4-43d0-a5ea-66f8946ec018.png)

**Comment by jie65535** [comment]
This is a bug. You can solve the problem by creating this folder in the directory
