### ISSUE TITLE
出现一个问题

### ISSUE THREAD

**Issue by listen1user** [jie65535/GrasscutterCommandGenerator#167]
---------------------------
错误
---------------------------
加载设置时异常：System.Configuration.ConfigurationErrorsException: 配置系统未能初始化 ---> System.Configuration.ConfigurationErrorsException: “.”(十六进制值 0x00)是无效的字符。 第 9 行，位置 1。 (C:\Users\Gigabyte\AppData\Local\GrasscutterTools\GrasscutterTools-v1.7.6.e_StrongName_din5cownvad4tclddayxrjptuyqqm15w\1.7.6.0\user.config line 9) ---> System.Xml.XmlException: “.”(十六进制值 0x00)是无效的字符。 第 9 行，位置 1。

   在 System.Xml.XmlTextReaderImpl.Throw(Exception e)

   在 System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)

   在 System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)

   在 System.Xml.XmlTextReaderImpl.ParseText()

   在 System.Xml.XmlTextReaderImpl.ParseElementContent()

   在 System.Xml.XmlTextReaderImpl.Read()

   在 System.Xml.XmlTextReader.Read()

   在 System.Configuration.XmlUtil.StrictReadToNextElement(ExceptionAction action)

   在 System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)

   在 System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)

   在 System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)

   在 System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

   --- 内部异常堆栈跟踪的结尾 ---

   在 System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)

   在 System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)

   在 System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()

   在 System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)

   --- 内部异常堆栈跟踪的结尾 ---

   在 System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)

   在 System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(InternalConfigEventArgs e)

   在 System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(String configPath, BaseConfigurationRecord configRecord)

   在 System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)

   在 System.Configuration.BaseConfigurationRecord.GetSection(String configKey)

   在 System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)

   在 System.Configuration.ConfigurationManager.GetSection(String sectionName)

   在 System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)

   在 System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)

   在 System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)

   在 System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)

   在 System.Configuration.SettingsBase.get_Item(String propertyName)

   在 System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)

   在 System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)

   在 GrasscutterTools.Properties.Settings.get_DefaultLanguage()

   在 GrasscutterTools.Program.Main()
---------------------------
确定   
---------------------------

**Comment by jie65535** [comment]
`C:\Users\Gigabyte\AppData\Local\GrasscutterTools\GrasscutterTools-v1.7.6.e_StrongName_din5cownvad4tclddayxrjptuyqqm15w\1.7.6.0\user.config`

把这个文件内容发一下，好像里面有点问题。

_顺便你可以通过Actions下载自动构建的最新版。_
