### ISSUE TITLE
未将对象引用设置到对象的实例 

### ISSUE THREAD

**Issue by WenBing2078** [jie65535/GrasscutterCommandGenerator#185]
使用grasscuttter v1.6.1，游戏客户端3.7，GcTools-v1.9.1，opencommand-1.6.0.jar
点击“发送验证码”后出现“未将对象引用设置到对象的实例”

（opencommand-1.5.3.jar无法在grasscuttter v1.61上启动）
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/d77ee6ab-c3d0-408a-b71c-60e630cb527b)
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/07eb68da-ebd6-4750-9b2d-00e3a16b4125)

**Comment by jie65535** [comment]
感谢反馈，问题看起来依然没有解决，控制台应该有异常日志的，请提供控制台日志以便分析。

**Comment by WenBing2078** [comment]
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/063ad6d4-4807-4695-b648-36f794e2a62c)
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/a28bc153-3c81-40b0-872a-f17b87c41de6)
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/12a05178-70cc-4917-8830-7c4a6d3404b9)

**Comment by jie65535** [comment]
好的，感谢反馈，现在已经修复，请尝试使用 v1.6.1 版本插件 https://github.com/jie65535/gc-opencommand-plugin/releases/tag/v1.6.1
