### ISSUE TITLE
[功能请求] 自定义命令支持快捷键触发

### ISSUE THREAD

**Issue by kamanya** [jie65535/GrasscutterCommandGenerator#190]
因為AttackModifier兩位作者都沒更新了
所以請問有沒有辦法增加快速鍵功能 
讓多組動作能夠不用一直切換按F5
不然只能回去玩3.2
感恩

**Comment by jie65535** [comment]
這是一個很好的建議，自定義命令允許使用自定義快捷鍵觸發，非常合理。

但是攻擊修改不只是釋放Gadget，還有諸如重複、擴散、清理等功能，這個週末我來更新一個攻擊修改插件吧。

**Comment by jie65535** [comment]
不对，我查看作者仓库发现别人已经更新到了GC 1.6.x 的新版本
 https://github.com/NotThorny/AttackModifier/releases

看来我不需要更新插件了，不过自定义快捷键的功能我还是会考虑增加。
