### ISSUE TITLE
无法连接到服务器

### ISSUE THREAD

**Issue by dezigenb** [jie65535/GrasscutterCommandGenerator#197]
现在我正在使用GC1.6.1，但是发现工具只支持到了1.5.0，恳求作者大大尽快更新

**Comment by jie65535** [comment]
早就支持最新版本了，新的命令例如过场动画之类的都添加了，只是首页的列表项可能忘记改了。

**Comment by dezigenb** [comment]
但是我连不上我的服务器，我访问这个http://127.0.0.1/status/server，能正常地返回数据，但是工具并不能连接上，显示连接超时

**Comment by jie65535** [comment]
请提供服务器启动日志和错误提示等信息

**Comment by dezigenb** [comment]
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/103154870/6999fd94-8f45-48eb-8ead-3ac645509cf3)

**Comment by dezigenb** [comment]
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/103154870/7f2db508-4c23-49ed-ac50-2dd6919585b6)

**Comment by dezigenb** [comment]
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/103154870/b1255e36-df94-4dd2-81ef-d207ff8a295f)

**Comment by jie65535** [comment]
需要加上端口号在后面。 `http://192.168.31.101:443`

**Comment by dezigenb** [comment]
连上了，谢谢
