### ISSUE TITLE
大佬你写的东西检测到有病毒

### ISSUE THREAD

**Issue by chie4hao** [jie65535/GrasscutterCommandGenerator#2]

**Comment by jie65535** [comment]
我使用了加壳工具对可执行文件进行了打包，我不确定是哪一个选项会引起杀毒程序工作。
我会尝试排除掉可能引起杀毒反应的选项，如果有人愿意为我测试那就更好了。
我会生成数个可执行文件，每个打包选项不一样，再逐个检查是否引起反应。
可以告诉我你是用什么工具查出病毒的吗？

**Comment by chie4hao** [comment]
> 我使用了加壳工具对可执行文件进行了打包，我不确定是哪一个选项会引起杀毒程序工作。 我会尝试排除掉可能引起杀毒反应的选项，如果有人愿意为我测试那就更好了。 我会生成数个可执行文件，每个打包选项不一样，再逐个检查是否引起反应。 可以告诉我你是用什么工具查出病毒的吗？

就是Chrome下载显示“失败 - 检测到病毒”

**Comment by chie4hao** [comment]
应该就是windows自带的病毒检测给干掉的，就是想确认一下，如果没病毒我就正常用了。

**Comment by jie65535** [comment]
=-= 我放病毒干啥，一个小工具，总共才做了两天。
我打包只是防止有人倒卖，因为真有人愿意出钱买。
过一段时间我会转成开源。

我现在生成了另一个版本，你重新在发布中下载试试，这次还会报告病毒吗？

**Comment by chie4hao** [comment]
> =-= 我放病毒干啥，一个小工具，总共才做了两天。 我打包只是防止有人倒卖，因为真有人愿意出钱买。 过一段时间我会转成开源。
> 
> 我现在生成了另一个版本，你重新在发布中下载试试，这次还会报告病毒吗？

现在不会报病毒了。可以close了

**Comment by Caponia** [comment]
Windows Defender检测到特洛伊木马= =

**Comment by Caponia** [comment]
你加的啥壳儿啊怎么这么离谱

**Comment by jie65535** [comment]
![image](https://user-images.githubusercontent.com/29452349/166620265-a5d1d528-9af5-422b-b7c6-48e29c7b7cb8.png)
我已经关了大部分选项了，我最早发的版本直接全选的 =-= 
现在只是纯混淆，不加壳了。还会报毒？
