### ISSUE TITLE
[i18n] English translation | 多语言支持

### ISSUE THREAD

**Issue by arub3do** [jie65535/GrasscutterCommandGenerator#20]
- Data source: https://github.com/renkin-atorie/GrasscutterResources

Open question: Does anyone know any note for `json`s in Resources?
疑问：有没有 dalao 知道以上 Resources 相关的文档/笔记/说明？

## English TODO

- [x] Animal.txt
- [x] Artifact.txt
- [x] ArtifactCat.txt
- [x] ArtifactMainAttribution.txt
- [x] ArtifactSubAttribution.txt
- [x] Avatar.txt
- [x] CustomCommands.txt
- [x] Item.txt
- [x] Monster.txt
- [x] NPC.txt
- [x] Ornament.txt
- [x] Scene.txt
- [x] Weapon.txt

<details>
<summary>Animal.txt</summary>

### Animal.txt

1. *Animal.txt*
```
28010101: 黄金蟹
```
`AnimalId=28010101`

2. *resources\ExcelBinOutput\AnimalDescribeExcelConfigData.json*
```json
    {
        "Id": 28010101,
        "NameTextMapHash": 657550247,
        "Icon": "UI_AnimalIcon_Crab_01"
    },
```
`AnimalId => NameTextMapHash=657550247`

3. *`resources\TextMap\TextMap*.json`*
```json
// resources\TextMap\TextMapCHS.json
  390020,6:     "657550247": "黄金蟹",

// resources\TextMap\TextMapEN.json
  351519,6:     "657550247": "Golden Crab",

...
```
`NameTextMapHash => Final Strings`

![image](https://user-images.githubusercontent.com/105265570/167863491-ab2a658e-0024-426a-b122-089553a00539.png)
</details>

**Comment by jie65535** [comment]
我写了一个TextMap浏览器的小工具，可以用正则搜索，但是目前只是搜那个ManualTextMap和TextMap*。

主要是为了实现另一个issue，把卡池预制做成下拉的功能。

另外分析出各种物品id的应该有人写好了脚本，我现在用的就是别人生成的文件。只是我找不到来源..

**Comment by HuYo-OS** [comment]
[dump_handbook.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/8692638/dump_handbook.zip)
可以试试这个

**Comment by jie65535** [comment]
> [dump_handbook.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/8692638/dump_handbook.zip) 可以试试这个

这个可以，我用的中文版的应该就是这个脚本生成的，但是我用的是更新版本的，还解析出了摆件之类的。
你发的这个版本应该是较早期的，不过也补充了不少文件了，非常感谢！

**Comment by jie65535** [comment]
@NekosakiSR 已经完成了剩余文件的翻译，因此关闭这个issue。
