### ISSUE TITLE
自订快捷键问题及座标建议

### ISSUE THREAD

**Issue by kamanya** [jie65535/GrasscutterCommandGenerator#200]
快捷键部份
目前使用自订快捷键下来 有很多惊艳之处 玩了一整晚 还不腻
但来回切换增加还是有点不便之处
可否在F5执行下面多一项 增加快捷键 会更好用
另外组合键部份可否增加独立键盘或alt+mouse键 等
座标建议部份
1.生成介面可否增加 勾选增加当前座选项 就不用pos一直查询了
2.生成物座标可否增加当前座标的x y z距离差距 
   目前https://github.com/snoobi-seggs/AttackInfusedWithItem的部份作者都没更新 
   攻击注入参数形同虚设

有其他的好键议 我再增加 目前想到这些常用部份

**Comment by jie65535** [comment]
现在已经支持将单独按键作为快捷键，不要求功能键。鼠标按键的话暂时没空研究，也不太建议。

如果你将生成坐标保留为0,0,0（不指定），应该会自动生成在玩家所在位置。

GC的spawn命令本身不支持设置相对位置。

**Comment by kamanya** [comment]
謝謝 目前這樣也很夠用 只差F5那列增加個快捷 或許 自己勤快點就好了 Q . Q

**Comment by jie65535** [comment]
我目前除了在左边目录以外只有在自定义的界面加了一个快捷跳转。在左边和在下面我觉得差别应该不大吧，因为本身直接添加也需要设定标签，不是一键完成的。

**Comment by kamanya** [comment]
了解 那我在想其他有用的功能 ^ ^
