### ISSUE TITLE
GrasscutterTools固定的快速鍵 除了F5 外 左邊項目可以固定為1234567890快速鍵? 還是自訂 

### ISSUE THREAD

**Issue by kamanya** [jie65535/GrasscutterCommandGenerator#201]
在GrasscutterTools左方的項目
主頁 遠程 快捷鍵 聖遺物 生成 物品 角色 ...這些項目 可否固定個快速鍵 1 2 3 4 5 6 7...或 自已設定 方便更快切換
我知道項目很多可能不夠用 但是編輯項目 切換 應該對使用者會更便利的  謝謝

當然這些快速鍵只對當前GrasscutterTools才有作用 像 F5那樣

**Comment by jie65535** [comment]
直接按数字的话，可能会和数字输入框冲突，现在用 `Alt+[0~9]` 的方式来支持切换页面。
