### ISSUE TITLE
没有权限执行此命令

### ISSUE THREAD

**Issue by Nuisaxnuisa** [jie65535/GrasscutterCommandGenerator#203]
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/142822809/0a5e150b-97ce-40d5-9844-3ec17b119e9d)

**Comment by jie65535** [comment]
使用控制台为自己分配权限，分配权限的命令可以在管理页面生成。

**Comment by Nuisaxnuisa** [comment]
> 使用控制台为自己分配权限，分配权限的命令可以在管理页面生成。

![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/142822809/2340addf-e90d-44c7-8017-d5548eca29ea)这样吗

**Comment by taurusduan** [comment]
> 控制台是指你启动GC服务器的那个黑窗口，这里是用来连接控制台的地方，不是在这里执行。

大哥请教一下：
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/30854760/9b16adfd-cfc2-42e9-a71f-1961b6b29f4b)
在后台使用
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/30854760/39e559a0-7f52-4e75-b8f1-56aebb1710ca)
我这个是什么地方又搞错了吗？拜托教教我。

**Comment by jie65535** [comment]
> > 控制台是指你启动GC服务器的那个黑窗口，这里是用来连接控制台的地方，不是在这里执行。
> 
> 请教一下，我这个是什么地方又搞错了吗？拜托教教我。

在控制台执行命令不要写 `/` ，去掉就行了。

建议有问题加群问，Github不能及时答复。
