### ISSUE TITLE
[功能请求]活动编辑器中活动类型、ID以及满足条件列表的意义不是很清晰

### ISSUE THREAD

**Issue by morikawa56** [jie65535/GrasscutterCommandGenerator#205]
在配置ActivityConfig.json的过程中不清楚这里的活动类型如何分类的，计划ID是什么以及满足条件列表该填入什么信息。
个人在4.0版本中直接添加活动会出现各种乱码及报错，导入了[Yukki佬的ActivityConfig.json](https://gitlab.com/YuukiPS/GC-Data/-/blob/main/data/ActivityConfig.json)进行分析发现填入了这些信息，而且游戏中并未报错，但是在任务ID和物品ID中均未找到满足条件列表中的信息。
想要知道这些信息如何填写。

**Comment by jie65535** [comment]
以前活动配置里只有ID和开始时间结束时间在GC里有处理的。可能是后续实现了部分？暂时不是很清楚这里面的变化。
至于这些ID，其实在RES里有对应的表格的，因为处理起来有些麻烦，所以没有添加到工具里，你可以用VSCode打开RES的目录，然后找找Activity相关的文件，可以分辨里面的作用。或者等我有时间再看看具体变化。

**Comment by morikawa56** [comment]
谢谢~~
