### ISSUE TITLE
找不到4.0怪物ID

### ISSUE THREAD

**Issue by WenBing2078** [jie65535/GrasscutterCommandGenerator#207]
![屏幕截图 2023-09-20 234316](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/174df9e0-c8f3-4745-abcb-55643f946be4)
![屏幕截图 2023-09-20 234253](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/26bc2422-281d-46bf-840c-80d5a83b8833)
![屏幕截图 2023-09-20 234355](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/59331f1f-e908-4737-ac89-f57a5ca8fdee)
![屏幕截图 2023-09-20 234340](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/976ec116-1832-4775-8c39-dbd6e7d28c5e)
![屏幕截图 2023-09-20 234452](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/b41cf49a-048a-4802-a2ee-baad732422e4)
![屏幕截图 2023-09-20 234439](https://github.com/jie65535/GrasscutterCommandGenerator/assets/109894308/8dc86bcd-7a23-4956-b647-ea8d131d1357)

**Comment by jie65535** [comment]
可以通过[这个提交](https://github.com/jie65535/GrasscutterCommandGenerator/commit/82668c4c6a47d5dc4dad6d3dec3370f5f1a6c771#diff-eee80f1f133da7415fcf639385183649389d0d8ea89b157304e0017131a96086)看到4.0到底新增了哪些ID。

**Comment by Ken-Parker** [comment]
> 可以通过[这个提交](https://github.com/jie65535/GrasscutterCommandGenerator/commit/82668c4c6a47d5dc4dad6d3dec3370f5f1a6c771#diff-eee80f1f133da7415fcf639385183649389d0d8ea89b157304e0017131a96086)看到4.0到底新增了哪些ID。

好奇这些名字是个人翻译的吗，我也蛮想去翻译哈哈🤣

**Comment by jie65535** [comment]
> > 可以通过[这个提交](https://github.com/jie65535/GrasscutterCommandGenerator/commit/82668c4c6a47d5dc4dad6d3dec3370f5f1a6c771#diff-eee80f1f133da7415fcf639385183649389d0d8ea89b157304e0017131a96086)看到4.0到底新增了哪些ID。
> 
> 好奇这些名字是您自己翻译的吗，我也蛮想去翻译哈哈🤣

这些名字不完全是自己翻译的，大部分是获取官方的文本，但后续没有新的了，所以如果你能帮忙翻译那最好不过了。

可能需要花费一些功夫在游戏中挨个生成。

**Comment by Ken-Parker** [comment]
> > > 可以通过[这个提交](https://github.com/jie65535/GrasscutterCommandGenerator/commit/82668c4c6a47d5dc4dad6d3dec3370f5f1a6c771#diff-eee80f1f133da7415fcf639385183649389d0d8ea89b157304e0017131a96086)看到4.0到底新增了哪些ID。
> > 
> > 
> > 好奇这些名字是您自己翻译的吗，我也蛮想去翻译哈哈🤣
> 
> 这些名字不完全是自己翻译的，大部分是获取官方的文本，但后续没有新的了，所以如果你能帮忙翻译那最好不过了。
> 
> 可能需要花费一些功夫在游戏中挨个生成。

不碍事，慢慢来。我如果翻译的话直接编辑Source/GrasscutterTools/Resources/zh-cn里的txt文档吗

**Comment by jie65535** [comment]
嗯，先在仓库上点Fork，你可以直接在自己的Github上修改，最后可以选择提交Pull Request来合并到仓库中。

**Comment by Ken-Parker** [comment]
> 嗯，先在仓库上点Fork，你可以直接在自己的Github上修改，最后可以选择提交Pull Request来合并到仓库中。

okay
