### ISSUE TITLE
卡池编辑没反应呀？

### ISSUE THREAD

**Issue by SalterYu** [jie65535/GrasscutterCommandGenerator#210]
卡池编辑和商城编辑没反应呀？该怎么用呢？谢谢回答一下！
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/24646250/8961c195-34c6-4364-9526-ac3a8524bc47)
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/24646250/d60751e4-0416-4dcc-a74a-ab87a9670b2b)

**Comment by jie65535** [comment]
卡池建议基于[现成的文件](https://github.com/Zhaokugua/Grasscutter_Banners)修改，商店可以用商店编辑器打开RES里的 `ShopGoodsExcelConfigData.json` 然后再保存成 `Shop.json`。
