### ISSUE TITLE
一键获取所有武器缺少白术的专武 碧落之珑 (itemID：14505)

### ISSUE THREAD

**Issue by Ken-Parker** [jie65535/GrasscutterCommandGenerator#212]
![image](https://github.com/jie65535/GrasscutterCommandGenerator/assets/33827973/f6a58a97-cac5-4135-bd81-82f15e4495ec)
如图：带有“新”字样的武器是刚刚点击 <一键获取所有武器> 获得的，并没有包括<碧落之珑>

**Comment by jie65535** [comment]
这是RES的问题，目前主流的RES里确实不包含这个武器，工具里是完整的。
