### ISSUE TITLE
活動編輯無反應!

### ISSUE THREAD

**Issue by smile850911** [jie65535/GrasscutterCommandGenerator#213]
請大大教學一下 不太懂如何使用

**Comment by jie65535** [comment]
使用活动编辑器生成活动配置文件，放到Grasscutter的data文件夹中，即可在游戏内查看到活动。

但实际上这些活动大概率无法进行，因为这需要服务端lua脚本支持。

**Comment by MineRiko** [comment]
> 使用活动编辑器生成活动配置文件，放到Grasscutter的data文件夹中，即可在游戏内查看到活动。
> 
> 但实际上这些活动大概率无法进行，因为这需要服务端lua脚本支持。

请问大佬以后会推出在“添加或更新活动”时自动替换服务端lua脚本的功能吗，或者烦请开一个贴，就像收集每个版本的卡池一样，收集一下各个活动的文件呢？小白表示真的不知道这怎么弄，麻烦了

**Comment by leez3sun** [comment]
> 請大大教學一下 不太懂如何使用

这个我修改过json文件了  只能更改活动列表的图片  不能实行    想看相关场景可以去添加相关活动任务
