### ISSUE TITLE
Command generator for Artifacts has a little misstake

### ISSUE THREAD

**Issue by RazorWolvendom** [jie65535/GrasscutterCommandGenerator#215]
/give 90544 lv20 10001  @943527

(There are 2 spaces for the playerID which makes the run command invalid always)

**Comment by jie65535** [comment]
The latest [commit](https://github.com/jie65535/GrasscutterCommandGenerator/commit/5b2442591f9a53f6b5481f5a8f731591c0f6c660) has fixed this issue, but a new version has not been released yet.

You can download automatic build from [here](https://github.com/jie65535/GrasscutterCommandGenerator/actions/runs/6838933488).

Thank you for your feedback.
