### ISSUE TITLE
邮件功能异常

### ISSUE THREAD

**Issue by Nyar-ko** [jie65535/GrasscutterCommandGenerator#216]
当发送全体邮件时，只会在数据库生成一个邮件id并不断刷新Uid，游戏内表现为接收到邮件，但无法领取，一旦玩家下线，该邮件就会消失，只有最后一位玩家邮件还在
![{136C933D-C463-4ad2-88C6-47BBE8BBC56A}](https://github.com/jie65535/GrasscutterCommandGenerator/assets/97618198/c5ba4745-51e7-47cf-a02b-06ca72a74755)

**Comment by jie65535** [comment]
这个问题应该反馈给GC，本工具只是根据命令格式通过GUI生成命令。
