### ISSUE TITLE
请问能更新一下适用于455的GCTool吗，感谢

### ISSUE THREAD

**Issue by Jtuiii** [jie65535/GrasscutterCommandGenerator#221]

**Comment by jie65535** [comment]
目前GC还没更新到4.5呢，GCT更新了也没有意义。 玩家都玩不上。

不过如果有4.5的RES，我也可以更新一个版本带新ID的。

**Comment by Jtuiii** [comment]
> 目前GC还没更新到4.5呢，GCT更新了也没有意义。玩家都玩不上。
> 
> 不过有的话4.5的RES，我也可以更新一个版本带新ID的。
4.5res
https://gitlab.com/Dimbreath/AnimeGameData/-/tree/main?ref_type=heads

**Comment by Jtuiii** [comment]
4.5res（万分感谢）：https://gitlab.com/Dimbreath/AnimeGameData/-/tree/main?ref_type=heads

**Comment by jie65535** [comment]
现已更新所有4.5ID，请等待从Action中下载1.14进行测试，没问题再发正式版。

**Comment by Jtuiii** [comment]
万分感谢jie佬





------------------ 原始邮件 ------------------
发件人: jie65535 ***@***.***&gt;
发送时间: 2024年3月25日 00:16
收件人: jie65535/GrasscutterCommandGenerator ***@***.***&gt;
抄送: Jtuiii ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [jie65535/GrasscutterCommandGenerator] 请问能更新一下适用于455的GCTool吗，感谢 (Issue #221)





 
现已更新所有4.5ID，请等待从Action中下载1.14进行测试，没问题再发正式版。
