### ISSUE TITLE
spawn怪物的时候提示场景内生成数量已达上限，替代为生成0实体

### ISSUE THREAD

**Issue by HelloMWH** [jie65535/GrasscutterCommandGenerator#223]
求助需要如何解决？之前生成的怪物也完成了击杀，但貌似还是提示上限

**Comment by jie65535** [comment]
这个需要服务端那边修复，工具这边没什么办法。

**Comment by HelloMWH** [comment]
> 这个需要服务端那边修复，工具这边没什么办法。

哦哦，是服务端侧要调整上限么？

**Comment by HelloMWH** [comment]
> 不只是调整上限的问题，理论上死掉的实体会被清理的，不然一直占用你上限多少也可能用完，而且服务端占用也高。 所以没有清理肯定是有什么BUG，需要修复才行。

嗯，貌似GC本身没提供这个清理的能力。
