### ISSUE TITLE
Suggestion: Complete all quests

### ISSUE THREAD

**Issue by Bogieloo** [jie65535/GrasscutterCommandGenerator#225]
Hey, i'm a big fan of this tool but quests are quiet annoying, it would be nice to be able to have a button that automatically completes all quests.

**Comment by jie65535** [comment]
At present, there is no command to complete all quests, but I can optimize the interaction on the quests page, such as checking the checkbox to automatically accept and complete the selected items, combined with the Shift splicing command, which can achieve similar effects.

**Comment by jie65535** [comment]
done.
