### ISSUE TITLE
可以增加一些可玩性lua的命令

### ISSUE THREAD

**Issue by Liujunhua007** [jie65535/GrasscutterCommandGenerator#230]
我最近在一些分支GC里看到，尤其是4.6 4.7，它们应用了lua文件，支持hideui,fps,speed等命令，可以搜集并放置到自定义里？

**Comment by jie65535** [comment]
可以啊，欢迎PR

**Comment by Liujunhua007** [comment]
> 可以啊，欢迎PR

大佬只能靠你啊，我不会程序代码啊，Skill issue捏

**Comment by jie65535** [comment]
如果不是官方GC的命令，不建议添加到gct原版里，因为那样这些命令可能用不了。

如果要改的话，可以直接编辑[这个文件](https://github.com/jie65535/GrasscutterCommandGenerator/blob/main/Source/GrasscutterTools/Resources/zh-cn/CustomCommands.txt)就有了。
