### ISSUE TITLE
在lunagc上无法解锁5.0地图锚点的问题

### ISSUE THREAD

**Issue by Lljjcc625** [jie65535/GrasscutterCommandGenerator#236]
如标题

**Comment by Jimmy32767255** [comment]
这很明显是由于您的服务端异常(比如资源不完整)导致的，与本指令生成工具无关。

**Comment by Jimmy32767255** [comment]
在您对任何项目发起任何反馈之前，请先确认这是谁的问题，谢谢

**Comment by Jimmy32767255** [comment]
要证明这不是本工具的问题，您只需要在服务器控制台中输入“prop unlockmap 1 @[您账号的UID]”或者在游戏中将“/prop unlockmap 1”发送到服务器账号即可，如果您在执行完上述操作后仍无法点亮娜塔地区的地图，那么这可以非常轻易的证明这是服务器的问题而非本指令生成工具的问题，请您关闭本issues，谢谢。
