### ISSUE TITLE
自动生成命令包含id的问题

### ISSUE THREAD

**Issue by hhyacg** [jie65535/GrasscutterCommandGenerator#24]
不知道为什么id前自动添加了一个@
![A1{UO54G93)R}Q~5H$XW56Q](https://user-images.githubusercontent.com/40420771/168285829-36402ef3-f627-47fb-b8c6-1577166ec8d8.png)

**Comment by jie65535** [comment]
因为现在版本的服务端指令中，目标玩家ID就是`@uid`的格式

**Comment by hhyacg** [comment]
抱歉，是我没看清楚
