### ISSUE TITLE
【功能】远程服务器命令控制

### ISSUE THREAD

**Issue by Omoinemie** [jie65535/GrasscutterCommandGenerator#32]
我把服务端建在云服务器上的，没法输入控制命令，就没法建账号等操作。希望能加个远程控制功能，在服务器插件里配置一个用户和密码，客户端连接验证后就可以发送服务端命令。

**Comment by jie65535** [comment]
我试着写了一下，然后我发现一件事，当前的指令系统不支持插件扩展控制台，换句话说，我可以做到以控制台身份执行命令，但是我没法得到命令执行的结果，也就是输出的消息。

所以... 请SSH到你的服务器，然后copy命令来执行吧 XD

PR里其实有指令系统的重构，那个重构允许插件扩展控制台，但还没有被合并，等消息吧~

**Comment by jie65535** [comment]
当然，还有一种解决方案，那就是不响应命令的执行输出，直接返回成功。

**Comment by jie65535** [comment]
1.3.1 已支持以控制台身份执行命令，缺陷就是上面说的无法得到执行结果输出。
