### ISSUE TITLE
Windows&腾讯云报毒

### ISSUE THREAD

**Issue by ZXAS007** [jie65535/GrasscutterCommandGenerator#39]
![Screenshot_2022-05-18-19-49-33-455_com.miui.gallery.png](https://user-images.githubusercontent.com/69531154/169032199-a74b7f7f-0c60-428b-8f05-65dbebe19f11.png)

**Comment by jie65535** [comment]
可能Windows认为`System.Diagnostics.Process.Start("https://github.com/jie65535/gc-opencommand-plugin");`是不安全的？

我没办法解决这个问题，因为我没有做任何不应该做的事情。

**Comment by ZXAS007** [comment]
完全去除联网模式！

**Comment by jie65535** [comment]
如果你愿意，你可以fork过去自己修改，我不会这么做。

**Comment by jie65535** [comment]
这是一个开源项目，如果不信任预编译二进制文件，可以克隆代码自行编译。
