### ISSUE TITLE
圣遗物副词条界面

### ISSUE THREAD

**Issue by winter12138** [jie65535/GrasscutterCommandGenerator#4]
每种圣遗物词条应该只有4种不同数值，但是这里面有大量相同的，应该可以去除一些重复项。

![image](https://user-images.githubusercontent.com/22698289/166401709-98bb4012-73d0-4d26-ab31-0b634a83948c.png)

**Comment by jie65535** [comment]
我优化了这个界面的逻辑，现在就像这样
![2-CustomArtifact](https://user-images.githubusercontent.com/29452349/166407339-3ad60ca3-a84d-4d7b-b496-2a67ce2c28c2.png)
