### ISSUE TITLE
角色数据选项能否怎加角色移动速度，跳跃高度等属性尼？

### ISSUE THREAD

**Issue by MyFreeGame** [jie65535/GrasscutterCommandGenerator#40]
角色数据选项能否怎加角色移动速度，跳跃高度等属性尼？

**Comment by jie65535** [comment]
速度的话，可以试试 `_base_speed` 和 `_speed_percent`

跳跃高度好像没有属性可以设置。

**Comment by jie65535** [comment]
emm 你不要忘记这个工具本身是命令生成器，选项只是用来生成命令的。

你可以试试把参数改成我上面说的这两个设置来看看。具体支持哪些参数可以参照命令说明。
