### ISSUE TITLE
指令生成器的一些小建议

### ISSUE THREAD

**Issue by INTERpig** [jie65535/GrasscutterCommandGenerator#42]
命令生成器：
1、生成物品：因为物品太多，是否可以出检索功能（或是我没找到检索功能在哪里）
2、角色突破：目前角色突破似乎只能手动突破，不能一键拉90，可以考虑出一个针对已有角色一键拉到指定等级的代码（生成角色的代码只对没有的角色生效；加经验只能加到未突破的上限）
3、生成的怪物是否可以自定义血量，这样可以更好的测试伤害

**Comment by jie65535** [comment]
>  生成物品：因为物品太多，是否可以出检索功能

列表上方的输入框即为搜索栏，可输入关键字过滤

> 角色突破、血量自定义

可以提交到服务端仓库，本工具并不能改变指令定义，只是生成指令。

**Comment by INTERpig** [comment]
好的，那关于突破、怪物血量之类的代码该如何输入呢？或者说是否有代码库可以参考

**Comment by jie65535** [comment]
@INTERpig 你可以到Grasscutter仓库里面查看指令的代码，可以增加自己的指令或者优化现有指令。代码都是开放的。

**Comment by INTERpig** [comment]
好的，谢谢
