### ISSUE TITLE
Windows安全中心报毒

### ISSUE THREAD

**Issue by danyeye** [jie65535/GrasscutterCommandGenerator#43]
# 先后三次下载，均被Windows安全中心删除并报出特洛伊病毒
![image](https://user-images.githubusercontent.com/74907885/169498050-18216f91-28c3-45da-bc48-e4b1180ff39a.png)

**Comment by jie65535** [comment]
拉代码编译吧，或者使用其它在线工具，例如mojoconsole。我无法解决这个问题。

![躺](https://user-images.githubusercontent.com/29452349/169498643-7e976856-3ffc-415a-82a6-8a1e7e14ebb8.gif)
