### ISSUE TITLE
[建议]复制的判断

### ISSUE THREAD

**Issue by WJXhhh** [jie65535/GrasscutterCommandGenerator#47]
我认为把CopyCommand方法由
`Clipboard.SetText(TxtCommand.Text);`
改成
`if (!string.IsNullOrEmpty(TxtCommand.Text))
            {
                Clipboard.SetText(TxtCommand.Text);
            }
            else
            {
                Clipboard.SetText(" ");
            }`
比较好，不然Visual Studio报错。

**Comment by jie65535** [comment]
谢谢你的建议，若还有其它改善意见，欢迎直接PR，也可以继续提出issue。
