### ISSUE TITLE
生成的数量好像和等级写反了

### ISSUE THREAD

**Issue by ahalpha** [jie65535/GrasscutterCommandGenerator#5]
如图
![image](https://user-images.githubusercontent.com/83562251/166412544-6963eae1-abd7-4bdd-bde7-c82be6336546.png)
![image](https://user-images.githubusercontent.com/83562251/166412583-9dde9f3f-9bae-4bf9-af24-2ad26eaf1610.png)

**Comment by jie65535** [comment]
检查了一下，是服务端改了参数顺序，原本是`spawn <entityId|entityName> [level] [amount]`的。
现在是`spawn <entityId> [amount] [level(monster only)]`了
我会在下个版本修复。

**Comment by ahalpha** [comment]
好的
