### ISSUE TITLE
无限体力nostamina显示未知指令

### ISSUE THREAD

**Issue by LoathG** [jie65535/GrasscutterCommandGenerator#52]
无限体力与任务请求指令均显示为未知指令
![QQ图片20220530011620](https://user-images.githubusercontent.com/106495543/170895173-b0d521df-d081-4501-b56a-61fafa2f33f7.png)

**Comment by jie65535** [comment]
服务端版本太旧了，不支持这些指令。
你需要拉dev分支自行构建，或者从Actions中下载dev分支的最新版本。

**Comment by LoathG** [comment]
> 服务端版本太旧了，不支持这些指令。 你需要拉dev分支自行构建，或者从Actions中下载dev分支的最新版本。

是Grasscutter.jar这个文件吗？

**Comment by jie65535** [comment]
对
