### ISSUE TITLE
添加任务指令显示未知指令

### ISSUE THREAD

**Issue by a15546787953** [jie65535/GrasscutterCommandGenerator#53]
如题，添加任务指令显示未知指令显示Unknown Command：quest

**Comment by jie65535** [comment]
Grasscutter v1.1.0 不支持 quest，你需要从Actions中下载dev分支的最新jar，或者自己拉dev分支build。

**Comment by a15546787953** [comment]
我并不太懂这方面的东西，可否简单介绍下下载途径，望不吝赐教

**Comment by jie65535** [comment]
你可以访问[这个Action](https://github.com/Grasscutters/Grasscutter/actions/runs/2404411915) 点击下方的 `Grasscutter` 来下载最新dev的jar。

**Comment by a15546787953** [comment]
这个解压出来的jar文件是直接丢进根目录里就可以吧

**Comment by jie65535** [comment]
是的，替代原来的那个jar就好了。

**Comment by a15546787953** [comment]
感谢您的耐心解答，祝好！
