### ISSUE TITLE
[置顶] 关于游戏客户端更新后白屏问题

### ISSUE THREAD

**Issue by nhajq** [jie65535/GrasscutterCommandGenerator#55]
游戏怎么跟更新啊，进不去了，出现图标后就白屏了

**Comment by WF-1117** [comment]
更新白屏进不去了 怎么办

**Comment by jie65535** [comment]
游戏更新到2.7以后，需要最新版开发分支的服务端才支持，且需要更新为2.7的resource文件夹。

**Comment by nhajq** [comment]
能具体说一下怎么操作吗，对这种知识不太懂

**Comment by jie65535** [comment]
1. 你拥有服务端，来源如下：
    1. 你从Grasscutter主仓库中下载的服务端：从主仓库开发分支中克隆最新代码，构建服务端。从资源仓库中切换到2.7分支下载最新资源。具体可以上Discord询问。
    2. 使用从其它地方分享的一键端或整合包：等待一键端或整合包作者更新2.7的一键端或整合包。
2. 你没有服务端，你只是玩家：请通知服主更新服务端以支持2.7

**Comment by a15546787953** [comment]
![屏幕截图(117)](https://user-images.githubusercontent.com/106503603/171182340-45c999d7-63d1-4f51-b7a2-dd2c8c900487.png)
编译到 .\gradlew jar 这一步的时候就报错了，百思不解

**Comment by kangming06** [comment]
> ![屏幕截图(117)](https://user-images.githubusercontent.com/106503603/171182340-45c999d7-63d1-4f51-b7a2-dd2c8c900487.png) 编译到 .\gradlew jar 这一步的时候就报错了，百思不解

建议检查java版本

**Comment by a15546787953** [comment]
> > ![屏幕截图(117)](https://user-images.githubusercontent.com/106503603/171182340-45c999d7-63d1-4f51-b7a2-dd2c8c900487.png) 编译到 .\gradlew jar 这一步的时候就报错了，百思不解
> 
> 建议检查java版本

版本是17.0.3.1

**Comment by a15546787953** [comment]
> @a15546787953 你可以直接从Actions中下载自动构建的jar，不一定非要自行构建。

没办法啊，jar用的1.1.2-dev，2.7的Graeecutter和resources都更新了，进入游戏就白屏然后报网络相应超时，只好自己一点点琢磨了233

**Comment by LoathG** [comment]
与此同时如果服务端的jar文件换成1.1.0，那么游戏内将会自动下载10G资源（本人并未下载，直接退出了）。都无法正常游玩
