### ISSUE TITLE
能否考虑生成圣遗物时使用套装名+部位的模式

### ISSUE THREAD

**Issue by Patrick-Ze** [jie65535/GrasscutterCommandGenerator#6]
如题，能否考虑将生成圣遗物界面改为使用套装名+部位的模式？即使用两个下拉框，例如冰套：
冰风迷途的勇士 + 生之花

目前的模式下直接使用圣遗物名字的话，其实比较难对应到圣遗物的部位，从圣遗物名字猜测它是哪个套装相对有可能，但是猜测它是哪个部位就比较难了。
如果大佬考虑做这个功能的话，我可以帮忙整理每个圣遗物套装+部位到圣遗物名字的映射，例如：
冰风迷途的勇士 + 生之花 -> 历经风雪的思念
谢谢~

**Comment by jie65535** [comment]
只要你能提供映射表，我可以实现这个功能。

**Comment by Patrick-Ze** [comment]
原来是有规律的，感谢说明，那就好整理了。见附件：
[ArtifactCat.txt](https://github.com/jie65535/GrasscutterCommandGenerator/files/8610242/ArtifactCat.txt)
每一行是套装名与对应ID的对应关系，中间用TAB分隔了，如果有需要的话也可以方便替换成其他分隔形式
```
行者之心	51
```
已实装数据来自 https://github.com/dvaJi/genshin-data ，78,86,99未实装或者已弃用，名字来自BWIKI和搜到的内鬼消息

**Comment by jie65535** [comment]
经过测试，在83号套装对应的部件不适配这套规律。

**Comment by Patrick-Ze** [comment]
83-87号是`祭*之人`套装，这几套都只有理之冠一个部位

**Comment by jie65535** [comment]
![2-CustomArtifact](https://user-images.githubusercontent.com/29452349/166463335-da1328fd-e957-485f-a245-f5927e84efda.png)
这逻辑是真繁琐，不过好在，我做出来了。
