### ISSUE TITLE
有没有无cd的代码 大佬！！！

### ISSUE THREAD

**Issue by cglofa** [jie65535/GrasscutterCommandGenerator#61]
就是技能没有冷却

**Comment by jie65535** [comment]
目前没有，不过你可以通过定制一个100%减CD的圣遗物来实现。

**Comment by cglofa** [comment]
大佬 我突然发现好像没有词条可以减cd QAQ

**Comment by jie65535** [comment]
![image](https://user-images.githubusercontent.com/29452349/171859061-ec6978f5-c01d-4518-be9e-fdb765d6c014.png)
如图

**Comment by cglofa** [comment]
好的!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月3日(星期五) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jie65535/GrasscutterCommandGenerator] 有没有无cd的代码 大佬！！！ (Issue #61)





 

 如图

**Comment by cglofa** [comment]
大佬你好你的远程执行插件我放在了plugins里打开游戏但是还是不行 就是打叉的 这个plugins是在Grasscutter目录下是吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jie65535/GrasscutterCommandGenerator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月3日(星期五) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jie65535/GrasscutterCommandGenerator] 有没有无cd的代码 大佬！！！ (Issue #61)





 

 如图

**Comment by jie65535** [comment]
是，但是插件的版本和服务端的版本有关，最新的插件只支持指定的服务端版本。如果你用的是旧版本服务端，可能不兼容新版本插件。具体可以查看插件的发布信息。

**Comment by cglofa** [comment]
好的 你这有新的服务端版本下载链接吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月3日(星期五) 晚上9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jie65535/GrasscutterCommandGenerator] 有没有无cd的代码 大佬！！！ (Issue #61)





 
是，但是插件的版本和服务端的版本有关，最新的插件只支持指定的服务端版本。如果你用的是旧版本服务端，可能不兼容新版本插件。具体可以查看插件的发布信息。

**Comment by jie65535** [comment]
直接去Gresscutter的仓库里，从最新的dev分支克隆，或者直接在actions里面下载自动构建的jar。 新版本支持2.7客户端的。  具体操作自行参阅wiki或者上Discord求助。这里不负责这些事情。

**Comment by cglofa** [comment]
好的大佬真的非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jie65535/GrasscutterCommandGenerator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月3日(星期五) 晚上9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jie65535/GrasscutterCommandGenerator] 有没有无cd的代码 大佬！！！ (Issue #61)





 
直接去Gresscutter的仓库里，从最新的dev分支克隆，或者直接在actions里面下载自动构建的jar。 新版本支持2.7客户端的。  具体操作自行参阅wiki或者上Discord求助。这里不负责这些事情。
