### ISSUE TITLE
求助一下大佬，run.cmd界面输入1会闪退

### ISSUE THREAD

**Issue by noviceman2** [jie65535/GrasscutterCommandGenerator#62]
大佬，请问在点开run.cmd之后弹出的那个Grasscutter One-Click Pack窗口输入1然后就会直接闪退是为啥呀，之前我因为一些事情把文件都删除了，然后再下载回来之后就出现输入1之后闪退的问题了

**Comment by jie65535** [comment]
你应该向为你提供一键包的作者反馈，而不是向我这个命令生成器工具的作者反馈，我完全不了解你使用的环境与情况，无法为你提供帮助。
