### ISSUE TITLE
请问在生成角色导致游戏卡死的问题如何解决？

### ISSUE THREAD

**Issue by ShiyeLi** [jie65535/GrasscutterCommandGenerator#63]
虽然有警告，但是还是手贱试了下= =加了个测试角色，结果角色没显示出来操作也卡死了。
另外想问一下GcChinese指的是discord上的吗

**Comment by jiawei21** [comment]
同问

**Comment by jie65535** [comment]
用命令删除帐号，然后重新创建帐号。

**Comment by ShiyeLi** [comment]
> 用命令删除帐号，然后重新创建帐号。

行不通，这样操作以后会无法登陆

**Comment by ShiyeLi** [comment]
额。。没有用过MongoDB，可以问一下创建的人物的相关数据在哪个配置文件里面吗？我下载的是某个一键包
![image](https://user-images.githubusercontent.com/44299133/172179563-3469d80d-d7a7-425a-8628-2dd7fdfe765d.png)

**Comment by jie65535** [comment]
数据保存在MongoDB中，服务端依赖该数据库运行。
实在不行就开个新号。不一定非要用原来的。

**Comment by ShiyeLi** [comment]
谢谢，我试试
