### ISSUE TITLE
好友为空，如何给server发送指令？

### ISSUE THREAD

**Issue by 12314654615616** [jie65535/GrasscutterCommandGenerator#72]
![image](https://user-images.githubusercontent.com/107707054/174341186-cf3d8910-90d7-4568-9806-05fcfb09f244.png)
大佬你好，请问一下进去之后好友里面是空的，怎么发送对应指令呢，或者server的id是多少呢？

**Comment by 12314654615616** [comment]
从如何注册账号那里就开始看不懂是具体哪个文件下了，求帮助

**Comment by jie65535** [comment]
我怎么感觉你这个是官方服务器？你需要按照wiki自己搭建服务端，或者加入他人服务端，才可以使用相关命令。

**Comment by 12314654615616** [comment]
![1](https://user-images.githubusercontent.com/107707054/174416630-48922d94-ea1c-4574-b2f3-6b45bdef8ff1.png)
![2](https://user-images.githubusercontent.com/107707054/174416637-f4a7d0e8-f833-4553-b155-6434a8e67a86.png)
![3](https://user-images.githubusercontent.com/107707054/174416640-98684921-389b-4357-9ce0-1b29d78aa31d.png)
请问一下这样是属于搭建成功了吗？用创建好的账号进去显示账号格式错误

**Comment by jie65535** [comment]
不清楚，服务端搭建与加入和本工具无关，你可以上Discord求助，因为我无法解决这些问题。
