### ISSUE TITLE
[WIP] GcTools-v1.5.0 ---- Gc-v1.2.2-dev

### ISSUE THREAD

**Issue by daxiwow** [jie65535/GrasscutterCommandGenerator#74]
现在很多命令都合并了 用法也不一样了
该give命令现在具有旧的giveall,giveart和givechar命令的功能。

give有关键字参数x<amount>, lv<level>,r<refinement>并且c<constellation>可以在命令的任何地方使用，就像@UIDcan 一样。 x<amount>也可以写成<amount>x, 并且lv<level>可以是l<level>or lvl<level>, 它们都可以链接在一起而没有空格, 例如lv90r5x10.

要提供所有项目，请执行give <all|weapons|mats|avatars> [x<amount>]. 上面的关键字参数都对此有效。

工件语法是give <artifactId> [mainPropId] [<appendPropId>[,<times>]].... x<amount>并lv<level>使用它，并注意它使用 0-20 的级别来匹配显示的游戏内数字而不是 1-21，尽管如果你喂它它不会抱怨lv21。

**Comment by daxiwow** [comment]
https://github.com/Grasscutters/Grasscutter/wiki/Commands

**Comment by jie65535** [comment]
v1.5.0 现在支持新的命令，可以在这里下载测试，稳定后再发布。

---
v1.5.0 now supports new commands, which can be downloaded and tested here, and released after stable.

[GrasscutterTools-v1.5.0-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9002124/GrasscutterTools-v1.5.0-debug.exe.zip)

**Comment by Herobrine-Jdts** [comment]
> v1.5.0 现在支持新的命令，可以在这里下载测试，稳定后再发布。
> 
> v1.5.0 now supports new commands, which can be downloaded and tested here, and released after stable.
> 
> [GrasscutterTools-v1.5.0-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9002124/GrasscutterTools-v1.5.0-debug.exe.zip)

还有无限能量那个命令，控制台不识别，prop得改成setprop

**Comment by jie65535** [comment]
> /changescene 命令已经被合并到 /tp 中了，或许切换场景的命令可以改成跟旁边的传送按钮（含场景ID）一样 ？

我改为忽略切换选中项事件了，集成到传送吧。

> 还有无限能量那个命令，控制台不识别，prop得改成setprop

这个在 #75  中修复了

现在已经更新了debug文件，还是从上面那个评论中下载。或者在这里也可以：[GrasscutterTools-v1.5.0-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9010264/GrasscutterTools-v1.5.0-debug.exe.zip)

计划如果没有更多修改的话，明天或者后天会发布正式版本。

**Comment by jie65535** [comment]
如果没有更多问题或者更改，今晚十点会正式发布1.5版本。

**Comment by devhxizm** [comment]
有可以关闭无限能量和无敌的指令吗

**Comment by jie65535** [comment]
> 有可以关闭无限能量和无敌的指令吗

`on` 改成 `off` 就可以了

**Comment by devhxizm** [comment]
问一下，私服放大招没有无敌帧是服务器问题还是说这个也是指令

**Comment by jie65535** [comment]
> 问一下，私服放大招没有无敌帧是服务器问题还是说这个也是指令

不清楚，也许是服务端的逻辑？毕竟造成伤害的逻辑都是服务端的代码。

**Comment by devhxizm** [comment]
无限能量的指令在_GrasscutterTools_上找不到

**Comment by jie65535** [comment]
> 无限能量的指令在_GrasscutterTools_上找不到

如果你在旧版本编辑过自定义命令，你需要重置才会加载新的资源。你可以导出现有列表，然后重置列表。

**Comment by devhxizm** [comment]
是重新加载服务器配置吗

**Comment by jie65535** [comment]
> 是重新加载服务器配置吗

不是，是工具的 `自定义` 页面，右上角有一个`重置`标签。

**Comment by devhxizm** [comment]
哦，我重置了之后出现了一个无限耐力的指令

**Comment by devhxizm** [comment]
> > 是重新加载服务器配置吗
> 
> 不是，是工具的 页面，右上角有一个标签。`自定义``重置`

我查了一下资料找到了关闭无限能量的指令，谢谢解答了
