### ISSUE TITLE
1.5.2版本打不开

### ISSUE THREAD

**Issue by qingchunnh** [jie65535/GrasscutterCommandGenerator#84]
双击之后鼠标一直转圈文件管理器也跟着卡了，1.4版本正常

**Comment by jie65535** [comment]
双击运行可执行文件无法启动？甚至连文件管理器也卡住？我没有复现出这个问题。

**Comment by qingchunnh** [comment]
> 双击运行可执行文件无法启动？甚至连文件管理器也卡住？我没有复现出这个问题。

已解决，右键选择兼容性疑难解答，然后系统默认给我选了windows8兼容性运行，然后就打开了我又把兼容性关掉就恢复正常了
