### ISSUE TITLE
奖池如何正确使用已经把生成的json复制到Banners里面但是游戏里面还没有效果

### ISSUE THREAD

**Issue by JingMinYe** [jie65535/GrasscutterCommandGenerator#89]
![image](https://user-images.githubusercontent.com/109449990/179384274-54754be7-1478-4942-a9e1-762ed6eef75f.png)
如何正确使用

**Comment by jie65535** [comment]
对象与对象之间用逗号隔开: `}, {`

**Comment by JingMinYe** [comment]
![image](https://user-images.githubusercontent.com/109449990/179390599-986e9b8b-0df4-4cd2-aaad-13fb2383d4e6.png)
隔开了打开游戏还是不行 难道下面那些数字也要加空格吗

**Comment by jie65535** [comment]
服务器启动有报错吗？发一下启动日志。

**Comment by JingMinYe** [comment]
服务器启动没有报错 日志是在哪里找的

**Comment by JingMinYe** [comment]
![Uploading image.png…]()
这个启动需要密码

**Comment by JingMinYe** [comment]
![image](https://user-images.githubusercontent.com/109449990/179391178-e7a3a534-c4f8-4928-94cf-1da7d0b2440f.png)

**Comment by jie65535** [comment]
启动服务器的时候，会弹出一个cmd窗口，窗口里滚动的就是服务器日志。如果json文件格式不正确，那么在服务器启动的时候就会报告错误，因此我需要这个日志信息。

或者你打开logs文件夹，里面有按日期划分的日志文件，其中`latest.log`就是最新的日志。

**Comment by JingMinYe** [comment]
我启动服务器的时候没有cmd窗口

**Comment by JingMinYe** [comment]
![image](https://user-images.githubusercontent.com/109449990/179391354-3d9e8781-f39d-42c4-bc29-bf391b98f477.png)

**Comment by jie65535** [comment]
你将完整的 `Banners.json` 复制到这里，不要发截图

**Comment by JingMinYe** [comment]
[latest.log](https://github.com/jie65535/GrasscutterCommandGenerator/files/9127313/latest.log)

**Comment by jie65535** [comment]
# **Banners.json**

**Comment by JingMinYe** [comment]
所以是什么问题呢

**Comment by jie65535** [comment]
我说的是把完整的 **Banners.json** 文件发出来，而不是 **latest.log**

**Comment by JingMinYe** [comment]
[Banners.txt](https://github.com/jie65535/GrasscutterCommandGenerator/files/9127329/Banners.txt)
由于json类型文件发送不了我修改了一下后缀

**Comment by JingMinYe** [comment]
[
	{
		"gachaType": 200,
		"scheduleId": 893,
		"bannerType": "STANDARD",
		"prefabPath": "GachaShowPanel_A022",
		"previewPrefabPath": "UI_Tab_GachaShowPanel_A022",
		"titlePath": "UI_GACHA_SHOW_PANEL_A022_TITLE",
		"costItemId": 224,
		"costItemAmount": 1,
		"costItemAmount10": 10,
		"beginTime": 0,
		"endTime": 1924992000,
		"sortId": 1000,
		"fallbackItems4Pool1": [1006, 1014, 1015, 1020, 1021, 1023, 1024, 1025, 1027, 1031, 1032, 1034, 1036, 1039, 1043, 1044, 1045, 1048, 1053, 1055, 1056, 1064],
		"weights4": [[1,510], [8,510], [10,10000]],
		"weights5": [[1,75], [73,150], [90,10000]]
	},
	{
		"gachaType": 301,
		"scheduleId": 903,
		"bannerType": "EVENT",
		"prefabPath": "GachaShowPanel_A086",
		"previewPrefabPath": "UI_Tab_GachaShowPanel_A086",
		"titlePath": "UI_GACHA_SHOW_PANEL_A045_TITLE",
		"costItemId": 223,
		"beginTime": 0,
		"endTime": 1659434340,
		"sortId": 9998,
		"rateUpItems4": [1059, 1027, 1050],
		"rateUpItems5": [1047],
		"fallbackItems5Pool2": [],
		"weights5": [[1,80], [73,80], [90,10000]]
	},
	{
		"gachaType": 400,
		"scheduleId": 923,
		"bannerType": "EVENT",
		"prefabPath": "GachaShowPanel_A087",
		"previewPrefabPath": "UI_Tab_GachaShowPanel_A087",
		"titlePath": "UI_GACHA_SHOW_PANEL_A018_TITLE",
		"costItemId": 223,
		"beginTime": 0,
		"endTime": 1659434340,
		"sortId": 9998,
		"rateUpItems4": [1059, 1027, 1050],
		"rateUpItems5": [1029],
		"fallbackItems5Pool2": [],
		"weights5": [[1,80], [73,80], [90,10000]]
	},
	{
		"gachaType": 302,
		"scheduleId": 913,
		"bannerType": "WEAPON",
		"prefabPath": "GachaShowPanel_A088",
		"previewPrefabPath": "UI_Tab_GachaShowPanel_A088",
		"titlePath": "UI_GACHA_SHOW_PANEL_A021_TITLE",
		"costItemId": 223,
		"beginTime": 0,
		"endTime": 1659434340,
		"sortId": 9997,
		"eventChance": 75,
		"softPity": 80,
		"hardPity": 80,
		"rateUpItems4": [11410, 15412, 12405, 13407, 14402],
		"rateUpItems5": [11503, 14502],
		"fallbackItems5Pool1": [],
		"weights4": [[1,600], [7,600], [8, 6600], [10,12600]],
		"weights5": [[1,100], [62,100], [73, 7800], [80,10000]]
	}，
                {               
                                 
 		 "gachaType":400,
 		 "scheduleId":800,
 		 "prefabPath":"GachaShowPanel_A013",
		  "previewPrefabPath":"UI_Tab_GachaShowPanel_A013",
		  "titlePath":"UI_GACHA_SHOW_PANEL_A013_TITLE",
 		 "costItem":223,
  		"beginTime":0,
		  "endTime":1924992000,
 		 "sortId":1000,
 		 "gachaTimesLimit":2147483647,
		  "rateUpItems4":[],
		  "rateUpItems5":[1016,1026,1030],
 		 "fallbackItems3":[11301,11302,11306,12301,12302,12305,13303,14301,14302,14304,15301,15302,15304],
		  "fallbackItems4Pool1":[1014,1020,1023,1024,1025,1027,1031,1032,1034,1036,1039,1043,1044,1045,1048,1053,1055,1056,1064],
  		"fallbackItems4Pool2":[11401,11402,11403,11405,12401,12402,12403,12405,13401,13407,14401,14402,14403,14409,15401,15402,15403,15405],
  		"fallbackItems5Pool1":[1003,1016,1035,1041,1042],
  		"fallbackItems5Pool2":[11501,11502,12501,12502,13502,13505,14501,14502,15501,15502],
		  "removeC6FromPool":false,
 		 "autoStripRateUpFromFallback":true,
 	 	"weights4":[[1,510],[8,510],[10,10000]],
  		"weights5":[[1,75],[73,150],[90,10000]],
 		 "poolBalanceWeights4":[[1,255],[17,255],[21,10455]],
 		 "poolBalanceWeights5":[[1,30],[147,150],[181,10230]],
		  "eventChance4":0,
		  "eventChance5":100,
 		 "bannerType":"EVENT"


	}，
	{
 		 "gachaType": 400,
  		"scheduleId": 10000,
 		 "bannerType": "EVENT",
 		 "prefabPath": "GachaShowPanel_A028",
 		 "previewPrefabPath": "UI_Tab_GachaShowPanel_A028",
		  "titlePath": "UI_GACHA_SHOW_PANEL_A028_TITLE",
		  "costItem": 224,
		  "beginTime": 0,
		  "endTime": 1924992000,
		  "sortId": 1000,
		  "rateUpItems1": [
  		  1030
 		 ],
 		 "rateUpItems2": [],
 		 "baseYellowWeight": 10000,
		  "basePurpleWeight": 10000,
 		 "eventChance": 100,
		  "softPity": 0,
 		 "hardPity": 0
	}，
	{
 		 "gachaType":400,
  		"scheduleId":807,
		  "prefabPath":"GachaShowPanel_A045",
 		 "previewPrefabPath":"UI_Tab_GachaShowPanel_A045",
 		 "titlePath":"UI_GACHA_SHOW_PANEL_A045_TITLE",
 		 "costItem":223,
 		 "beginTime":0,
 		 "endTime":1924992000,
		  "sortId":1000,
		  "gachaTimesLimit":2147483647,
  		"rateUpItems4":[],
 		 "rateUpItems5":[1047],
		  "fallbackItems3":[11301,11302,11306,12301,12302,12305,13303,14301,14302,14304,15301,15302,15304],
  		"fallbackItems4Pool1":[1014,1020,1023,1024,1025,1027,1031,1032,1034,1036,1039,1043,1044,1045,1048,1053,1055,1056,1064],
  		"fallbackItems4Pool2":[11401,11402,11403,11405,12401,12402,12403,12405,13401,13407,14401,14402,14403,14409,15401,15402,15403,15405],
 		 "fallbackItems5Pool1":[1003,1016,1035,1041,1042],
  		"fallbackItems5Pool2":[11501,11502,12501,12502,13502,13505,14501,14502,15501,15502],
  		"removeC6FromPool":false,
 		 "autoStripRateUpFromFallback":false,
  		"weights4":[[1,510],[8,510],[10,10000]],
  		"weights5":[[1,75],[73,150],[90,10000]],
  		"poolBalanceWeights4":[[1,255],[17,255],[21,10455]],
 		 "poolBalanceWeights5":[[1,30],[147,150],[181,10230]],
 		 "eventChance4":0,
 	 	"eventChance5":100,
  		"bannerType":"EVENT"
	}，
	{ 
 		 "gachaType":400,
  		"scheduleId":800,
		  "prefabPath":"GachaShowPanel_A007",
 		 "previewPrefabPath":"UI_Tab_GachaShowPanel_A007",
 		 "titlePath":"UI_GACHA_SHOW_PANEL_A007_TITLE",
 		 "costItem":224,
		  "beginTime":0,
		  "endTime":1924992000,
  		"sortId":1000,
		  "gachaTimesLimit":2147483647,
 		 "rateUpItems4":[],
  		"rateUpItems5":[1016],
 		 "fallbackItems3":[11301,11302,11306,12301,12302,12305,13303,14301,14302,14304,15301,15302,15304],
  		"fallbackItems4Pool1":[1014,1020,1023,1024,1025,1027,1031,1032,1034,1036,1039,1043,1044,1045,1048,1053,1055,1056,1064],
		  "fallbackItems4Pool2":[11401,11402,11403,11405,12401,12402,12403,12405,13401,13407,14401,14402,14403,14409,15401,15402,15403,15405],
  		"fallbackItems5Pool1":[1003,1016,1035,1041,1042],
		  "fallbackItems5Pool2":[11501,11502,12501,12502,13502,13505,14501,14502,15501,15502],
  		"removeC6FromPool":false,
  		"autoStripRateUpFromFallback":true,
  		"weights4":[[1,510],[8,510],[10,10000]],
		  "weights5":[[1,75],[73,150],[90,10000]],
  		"poolBalanceWeights4":[[1,255],[17,255],[21,10455]],
 		 "poolBalanceWeights5":[[1,30],[147,150],[181,10230]],
 		 "eventChance4":100,
 		 "eventChance5":100,
  		"bannerType":"STANDARD"
	}
]

**Comment by jie65535** [comment]
错误的原因是因为你使用了中文格式的逗号 `，`  这不是合法格式，修改为英文逗号 `,` 即可，我建议你下载一个 [VSCode](https://code.visualstudio.com) 以便于更好的编辑，因为错误的json在vscode中会报错。

我帮你修改了，顺手格式化了一下。
[Banners.txt](https://github.com/jie65535/GrasscutterCommandGenerator/files/9127338/Banners.txt)

**Comment by JingMinYe** [comment]
已修改后缀放入之前文件夹里但是打开游戏里面还是没有效果

**Comment by jie65535** [comment]
还有可能是因为那些 `gachaType` 和 `scheduleId` 数字重复了，你可以再试试都改成不一样的。

**Comment by JingMinYe** [comment]
已修改很多个了 但是重新打开游戏进去都没有效果

**Comment by jie65535** [comment]
没有效果是什么意思，卡池是空的还是和没改一样？

**Comment by JingMinYe** [comment]
没改

**Comment by JingMinYe** [comment]
卡池和之前一模一样

**Comment by jie65535** [comment]
那你把原本的卡池删掉其中一个，验证一下你的修改有没有效果。

**Comment by JingMinYe** [comment]
我把原来的卡池换成我修改的代码 如何游戏里面的卡池没有任何变化

**Comment by JingMinYe** [comment]
我把原来的卡池换成我修改的代码 然后游戏里面的卡池没有任何变化

**Comment by jie65535** [comment]
说明服务器根本没有加载你修改的卡池文件，你确定你连的自己打开的服务器吗？`Banners.json`是在data文件夹目录下吗？

**Comment by JingMinYe** [comment]
是的

**Comment by jie65535** [comment]
那我也没有办法了，卡池文件应该是正确的，问题可能出在其它地方，你可以上频道求助，或者去一些相关的群里问问。

**Comment by JingMinYe** [comment]
OK 谢谢拉

**Comment by JingMinYe** [comment]
自建了一个服务器搞了奖池代码进去了但是 进去游戏卡池没有界面什么都没有
![image](https://user-images.githubusercontent.com/109449990/179474566-b3cabe3d-274e-4830-bdce-416e10ef5755.png)

**Comment by JingMinYe** [comment]
![image](https://user-images.githubusercontent.com/109449990/179474622-f5059380-650e-4e5d-a59a-ef4e750ab2bf.png)

**Comment by JingMinYe** [comment]
![image](https://user-images.githubusercontent.com/109449990/179474669-64774bbb-bdc7-4589-bf5e-d4f2a7fb58d6.png)

**Comment by jie65535** [comment]
请提供日志文件

**Comment by JingMinYe** [comment]
[latest.log](https://github.com/jie65535/GrasscutterCommandGenerator/files/9130575/latest.log)

**Comment by JingMinYe** [comment]
![image](https://user-images.githubusercontent.com/109449990/179476938-cf219327-86c2-4a5a-a7ce-e62dac88a4d8.png)

**Comment by jie65535** [comment]
从头来一遍，把现在的`Banners.json`备份，然后启动服务器，自动生成默认的`Banners.json`文件，基于该文件，再单个添加你修改的卡池进行测试。

**Comment by JingMinYe** [comment]
修改卡池已经修改成功了但是我设置的百分百五星概率 没效果是设置错了了吗，新卡池和旧卡池都是这样子设置的 游戏里面也有卡池了 但是不是百分百出五星
![image](https://user-images.githubusercontent.com/109449990/179691342-a72955f8-79b5-46c1-b1a1-7abc221eff89.png)
![image](https://user-images.githubusercontent.com/109449990/179691546-2088c8d5-78c0-448a-acec-9afc22f7ea0c.png)

**Comment by JingMinYe** [comment]
softPity 最少几次出
 hardPity 最多几次出
这个几个好像设置1次 在游戏里面没有效果

**Comment by jie65535** [comment]
5星权重改成 `[[1, 10000], [2, 10000]]` 试试，我的工具只是生成符合要求的json，具体处理我也不清楚。

**Comment by liuxiaom-1** [comment]
![Uploading uTools_1678811721193.png…]()
有没有大佬知道这个怎么解决
