### ISSUE TITLE
切换场景完全用不了

### ISSUE THREAD

**Issue by moyuerr** [jie65535/GrasscutterCommandGenerator#9]
指令输进去之后没有反应

话说这个私服只能打打大地图上的怪么，可不可以做主线任务或者打副本呢

**Comment by jie65535** [comment]
大部分场景是没有用的，可能只有少部分场景有效果。
这些场景是导出的ID，我也没有验证哪些是有效的。
至于服务器，目前任务这块没做，副本也没做，功能还很不完善。
