### ISSUE TITLE
无法连接到服务器是怎么回事

### ISSUE THREAD

**Issue by chazime** [jie65535/GrasscutterCommandGenerator#91]
如图所示，分别为不同地点的两台机器的效果
![issue](https://user-images.githubusercontent.com/66537120/179904691-5b89ae18-1fdf-4117-b856-73a0ec1eaf51.png)

**Comment by jie65535** [comment]
现在解决了吗？请确认你的服务器地址是否正确。
我注意到你使用了http，那么你绑定的端口是80吗？如果不是，你需要指定端口号在地址中。

**Comment by chazime** [comment]
> 现在解决了吗？请确认你的服务器地址是否正确。 我注意到你使用了http，那么你绑定的端口是80吗？如果不是，你需要指定端口号在地址中。

经过指点，现在改了端口正常了，谢谢指导
![O(W1HZLQ8 VGZA%B}}VFWLQ](https://user-images.githubusercontent.com/66537120/180604798-14250608-97af-4177-93d2-ec48e16e50d5.jpg)
