### ISSUE TITLE
关于地图点亮

### ISSUE THREAD

**Issue by Audience03** [jie65535/GrasscutterCommandGenerator#92]
锚点和神像都是亮的但地图未点亮，如何点亮地图？有没有指令可以执行？

**Comment by jie65535** [comment]
感谢你的赞赏。本工具只是以可视化方式生成命令以便于玩家使用，你可以 [点击这里](https://github.com/Grasscutters/Grasscutter/wiki/Commands) 查看所有服务端支持的命令。

**Comment by Audience03** [comment]
所以说点亮地图是没有办法通过指令实现的吗？

**Comment by jie65535** [comment]
emm 好像确实没有这样的指令，也许你可以向Gresscutter提一个issue。

**Comment by Audience03** [comment]
我遇到的情况是锚点和神像都是可传送状态，但地图未点亮。所以，我需要的是点亮地图的方法，无论是以何种方式（笑哭）

**Comment by jie65535** [comment]
额，但是我也不知道有什么方法，所以没法帮助你解决问题，也许你可以去discord中问问。这个工具只是单纯的生成并执行命令而已。

**Comment by Audience03** [comment]
好吧，总而言之，谢谢大佬分享

**Comment by blurred11** [comment]
Gresscutter的issue里有解决方案哈哈
