### ISSUE TITLE
错误：在工具内导入存档时出现该问题

### ISSUE THREAD

**Issue by Libetr** [jie65535/GrasscutterCommandGenerator#96]
![image](https://user-images.githubusercontent.com/94942088/181310828-a0ae0cdc-3d54-49c5-93b1-4b1181c5b0d6.png)

**Comment by jie65535** [comment]
请你使用这个版本再试一次，并且将结果发送与此，谢谢。
[GrasscutterTools-v1.5.5-debug.exe.zip](https://github.com/jie65535/GrasscutterCommandGenerator/files/9204370/GrasscutterTools-v1.5.5-debug.exe.zip)

**Comment by Libetr** [comment]
![image](https://user-images.githubusercontent.com/94942088/181419326-8d0f4599-7729-4665-b6ff-81a160c32829.png)
你好，1.5.5版本可以使用
