### ISSUE TITLE
你好大佬，感谢您的软件，我想请教如何使用奖池编辑器

### ISSUE THREAD

**Issue by curryyinxh** [jie65535/GrasscutterCommandGenerator#99]

**Comment by curryyinxh** [comment]
目前正在参考之前的回答 进行尝试

**Comment by curryyinxh** [comment]
> 目前正在参考之前的回答 进行尝试
[卡池相关教程.txt](https://github.com/jie65535/GrasscutterCommandGenerator/files/9266426/default.txt)

**Comment by haifengdeweidao** [comment]
感谢分享！！
